# Generated by Django 4.1.2 on 2022-10-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_book_readers_alter_book_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="rate",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Waste of time"),
                    (2, "Hard to read"),
                    (3, "Good"),
                    (4, "Must read"),
                    (5, "Best"),
                ],
                null=True,
            ),
        ),
    ]
